swagger: "2.0"

info:
  description: Kruise deployment wizard
  title: Kruise deployment wizard
  version: 0.0.1

consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /deployment:
    post:
      tags:
      - deployments
      operationId: createDeployment
      description: Generates a new Kruise deployment
      parameters:
      - name: application
        in: body
        description: The application to create
        required: true
        schema:
          $ref: "#/definitions/application"
      responses:
        201:
          description: created
          schema:
            $ref: "#/definitions/application"
        400:
          $ref: "#/responses/BadRequest"
        default:
          $ref: "#/responses/InternalServerError"
  /health:
    get:
      tags:
      - general
      operationId: getHealth
      description: Get the current health of the API
      responses:
        200:
          description: Get current health response
          schema:
            $ref: "#/definitions/healthStatus"
        default:
          description: Error response
          schema:
            $ref: "#/definitions/error"

responses:
  BadRequest:
    description: Bad request
    schema:
      type: string
  InternalServerError:
    description: Internal server error
    schema:
      type: string

definitions:
  application:
    type: object
    properties:
      name:
        type: string
        minLength: 1
      tenant:
        type: string
        minLength: 1
    required:
    - name

  healthStatus:
    type: object
    properties:
      status:
        type: string
  error:
    type: object
    required:
    - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
