apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.App.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.App.Name}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.App.Name}}
    spec:
      containers:
      - name: {{.App.Name}}
        image: {{.Container.Image}}:{{.Container.ImageTag}}
        imagePullPolicy: {{.Container.ImagePullPolicy}}
        ports:
        {{- range .Service.Ports }}
        - name: {{.Name}}
          {{- if .TargetPort }}
          containerPort: {{.TargetPort}}
          {{- else }}
          containerPort: {{.Port}}
          {{- end }}
          protocol: {{.Protocol}}
        {{- end }}
