apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Service.Name}}
  labels:
    app: {{.App.Metadata.Name}}
    component: {{.Service.Name}}
    release: {{.App.Metadata.Labels.Version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.App.Metadata.Name}}
      component: {{.Service.Name}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.App.Metadata.Name}}
        component: {{.Service.Name}}
        release: {{.App.Metadata.Labels.Version}}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{.App.Metadata.Name}}
                  component: {{.Service.Name}}
                  release: {{.App.Metadata.Labels.Version}}
              topologyKey: kubernetes.io/hostname
            weight: 100
      volumes:
      - name: ca-bundles
        configMap:
          name: ca-bundles
      {{- range .ConfigMapNames }}
      - name: {{.}}
        configMap:
          name: {{.}}
      {{- end }}
      {{- range .PersistentVolumeNames }}
      - name: {{.}}
        persistentVolumeClaim:
          claimName: {{.}}
      {{- end }}
      containers:
      {{- range .Containers }}
      - name: {{.Name}}
        image: {{.Image}}:{{.ImageTag}}
        imagePullPolicy: {{.ImagePullPolicy}}
        {{- if .Command }}
        command: [{{.Command}}]
        {{- end }}
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-bundles
          readOnly: true
        {{- range .Volumes }}
        - mountPath: {{.MountPath}}
          name: {{.Name}}
          readOnly: {{.ReadOnly}}
          {{- if .SubPath }}
          subPath: {{.SubPath}}
          {{- end }}
        {{- end}}
        ports:
        {{- range $containerPort := .PortNames }}
        {{- range $servicePort := $.Service.Ports }}
        {{- if eq $containerPort $servicePort.Name}}
        - name: {{$servicePort.Name}}
          {{- if $servicePort.TargetPort }}
          containerPort: {{$servicePort.TargetPort}}
          {{- else }}
          containerPort: {{$servicePort.Port}}
          {{- end }}
          protocol: {{$servicePort.Protocol}}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
