apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: {{.applicationName}}-ingress
  name: {{.applicationName}}-ingress
spec:
  rules:
{{- range .services }}
  - host: {{.hostFQDN}}
    http:
      paths:
      - backend:
          serviceName: {{.serviceName}}
          servicePort: {{.servicePort}}
{{- if .servicePath }}
        path: {{.servicePath}}
{{- end }}
{{- end }}
