apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{persistent-volume-claim-name-pvc}}
spec:
  accessModes:
  - [[ReadWriteOnce,ReadOnlyMany,ReadWriteMany]]
  resources:
    requests:
      storage: {{size-in-gigabytes}}
  storageClassName: {{available storage classes}}
