apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{.Service.Name}}
    app: {{.App.Name}}
    release: {{.App.Release}}
    {{- if  .Service.Tier}}
    tier: {{ .Service.Tier}}
    {{- end }}
  name: {{.Service.Name}}
spec:
  ports:
  {{- range .Service.Ports }}
  - name: {{.Name}}
    port: {{.Port}}
    protocol: {{.Protocol}}
    {{- if .TargetPort }}
    targetPort: {{.TargetPort}}
    {{- end }}
  {{- end }}
  selector:
    app: {{.App.Name}}
    component: {{.App.Name}}
  type: {{.Service.Type}}
